[package]
name = "fn-util"
version = "0.1.0"
edition = "2021"
description = "A proc macro contains utilities for rust functions"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = {version="1", features=["full"]}
quote = "1"